#!/bin/bash
rm libs/armeabi/libcore.so
rm obj/local/armeabi/libcore.so
rm libs/armeabi-v7a/libcore.so
rm obj/local/armeabi-v7a/libcore.so
cp ../mupen64plus-core-ARCHs/libs/armeabi/libcore.so libs/armeabi/
cp ../mupen64plus-core-ARCHs/libs/armeabi/libcore.so obj/local/armeabi/
cp ../mupen64plus-core-ARCHs/libs/armeabi-v7a/libcore.so libs/armeabi-v7a/
cp ../mupen64plus-core-ARCHs/libs/armeabi-v7a/libcore.so obj/local/armeabi-v7a/

