LOCAL_PATH := $(call my-dir)

########## AE-IMPORTS ##########

include $(CLEAR_VARS)

LOCAL_MODULE := ae-imports

LOCAL_C_INCLUDES := $(M64P_API_INCLUDES) $(SDL_INCLUDES)

LOCAL_SRC_FILES := ae_imports.cpp

LOCAL_CFLAGS := $(COMMON_CFLAGS)

LOCAL_CPPFLAGS := $(COMMON_CPPFLAGS)

LOCAL_LDLIBS := -llog

include $(BUILD_SHARED_LIBRARY)

########## AE-EXPORTS ##########

include $(CLEAR_VARS)

LOCAL_MODULE := ae-exports

LOCAL_SHARED_LIBRARIES := ae-imports SDL2 core front-end

LOCAL_C_INCLUDES := $(M64P_API_INCLUDES) $(SDL_INCLUDES)

LOCAL_SRC_FILES := ae_exports.cpp

LOCAL_CFLAGS := $(COMMON_CFLAGS)

LOCAL_CPPFLAGS := $(COMMON_CPPFLAGS)

LOCAL_LDLIBS := -llog

include $(BUILD_SHARED_LIBRARY)
