LOCAL_PATH := $(call my-dir)

########## AE-IMPORTS ##########

include $(CLEAR_VARS)

LOCAL_MODULE := ae-imports

LOCAL_SHARED_LIBRARIES := SDL2

LOCAL_C_INCLUDES := $(M64P_API_INCLUDES)

LOCAL_SRC_FILES := ae_imports.cpp

LOCAL_CFLAGS := $(COMMON_CFLAGS)

LOCAL_CPPFLAGS := $(COMMON_CPPFLAGS)

LOCAL_LDFLAGS := $(COMMON_LDFLAGS)

LOCAL_LDLIBS := -llog

include $(BUILD_SHARED_LIBRARY)

########## AE-EXPORTS ##########

include $(CLEAR_VARS)

LOCAL_MODULE := ae-exports

LOCAL_SHARED_LIBRARIES := ae-vidext SDL2

LOCAL_C_INCLUDES := $(M64P_API_INCLUDES)

LOCAL_SRC_FILES := ae_exports.cpp

LOCAL_CFLAGS := $(COMMON_CFLAGS)

LOCAL_CPPFLAGS := $(COMMON_CPPFLAGS)

LOCAL_LDFLAGS := $(COMMON_LDFLAGS)

LOCAL_LDLIBS := -llog

include $(BUILD_SHARED_LIBRARY)

########## AE-VIDEXT ##########

include $(CLEAR_VARS)

LOCAL_MODULE := ae-vidext

LOCAL_SHARED_LIBRARIES := ae-imports SDL2

LOCAL_STATIC_LIBRARIES := EGLLoader

LOCAL_C_INCLUDES := $(M64P_API_INCLUDES) $(GL_INCLUDES)

LOCAL_SRC_FILES := ae_vidext.cpp

LOCAL_CFLAGS := $(COMMON_CFLAGS) -DEGL

LOCAL_CPPFLAGS := $(COMMON_CPPFLAGS) -std=c++11 -g

LOCAL_LDFLAGS := $(COMMON_LDFLAGS)

LOCAL_LDLIBS := -llog -lEGL -landroid

include $(BUILD_SHARED_LIBRARY)
