include $(CLEAR_VARS)
LOCAL_PATH := $(JNI_LOCAL_PATH)
SRCDIR := GL

LOCAL_ARM_MODE := arm
LOCAL_MODULE:= EGLLoader

LOCAL_C_INCLUDES +=   \
    $(LOCAL_PATH)/$(SRCDIR)
	
LOCAL_SRC_FILES:= \
	$(SRCDIR)/GL/EGLLoader.cpp

LOCAL_CFLAGS := -DEGL

LOCAL_CPPFLAGS := $(COMMON_CPPFLAGS) -Wno-unused-value -std=c++11

include $(BUILD_STATIC_LIBRARY)
