LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE := mupen64plus-input-raphnet
LOCAL_C_INCLUDES := $(M64P_API_INCLUDES)
LOCAL_SRC_FILES := plugin.c
LOCAL_CFLAGS := $(COMMON_CFLAGS)
LOCAL_LDFLAGS := $(COMMON_LDFLAGS)
LOCAL_LDLIBS := -llog

include $(BUILD_SHARED_LIBRARY)
